#!/bin/bash

# speedtest-cli --simple
/home/pi/pi/display/display "Testing speed.."
readarray -t array <<< "$(/usr/local/bin/speedtest --simple)"
echo array
/home/pi/pi/display/display "${RESULT[1]}" "${RESULT[4]}" "${RESULT[7]}"
