#!/usr/bin/python
# -*- coding:utf-8 -*-

import epd2in13
import time
from PIL import Image,ImageDraw,ImageFont
#import traceback
import sys

#display "$(date) \n $(host raspberrypi | grep 'address' | cut -d' ' -f4)"

font = ImageFont.truetype("/home/pi/pi/display/OverpassMono-Regular.ttf", 20, encoding="unic")

title = sys.argv[1]

epd = epd2in13.EPD()
epd.init(epd.FULL_UPDATE)
epd.Clear(0xFF)

image = Image.new('1', (epd2in13.EPD_HEIGHT, epd2in13.EPD_WIDTH), 255)  # 255: clear the frame
draw = ImageDraw.Draw(image)

lineHeight = 24
currentLine = 20

for argument in sys.argv:
    if sys.argv[0] != argument:
        draw.text((20, currentLine), argument, font=font)
        currentLine += lineHeight

# Drawing on the image

#draw.text((8, 8), title, fill=(255, 255, 255), font=font)

# Rotate
angle = 180
image = image.rotate(angle, expand=True)

epd.display(epd.getbuffer(image))
